name: "\U0001F41B Bug report(提交bug)"
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        请在 https://github.com/zyg1923/electerm 反馈问题，并尽量写清版本和系统。

  - type: input
    attributes:
      label: Electerm Version and download file extension(Electerm版本和下载文件后缀)
      description: |
        - electerm-xx.xx.xx-linux-amd64.deb
        - electerm-xx.xx.xx-linux-amd64.snap
        - electerm-xx.xx.xx-linux-x64.tar.gz
        - electerm-xx.xx.xx-linux-x86_64.rpm
        - electerm-xx.xx.xx-mac-arm64.dmg
        - electerm-xx.xx.xx-mac-x64.dmg
        - electerm-xx.xx.xx-win-x64-installer.exe
        - electerm-xx.xx.xx-win-x64-loose.tar.gz
        - electerm-xx.xx.xx-win-x64.appx
        - electerm-xx.xx.xx-win-x64.tar.gz
    validations:
      required: true
  - type: input
    attributes:
      label: Platform detail (平台详情)
      description: |
        windows 7/8/10/11, mac os(ARM or x64), or linux
        UNIX: output of `uname -a`
        Windows: output of `"$([Environment]::OSVersion | ForEach-Object VersionString) $(if ([Environment]::Is64BitOperatingSystem) { "x64" } else { "x86" })"` in PowerShell console
    validations:
      required: true
  - type: textarea
    attributes:
      label: What steps will reproduce the bug?(重现问题的详细步骤)
      description: Enter details about your bug, preferably a simple code snippet that can be run using `node` directly without installing third-party dependencies.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What should have happened?(期望的结果)
      description: If possible please provide screenshots.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)
      description: really important.
  - type: textarea
    attributes:
      label: Additional information(其他任何相关信息)
      description: Tell us anything else you think we should know.
